DynamicWrapperEx: CDynamicWrapperEx Class Reference
CDynamicWrapperEx Class Reference
DynamicWrapperEx class factory.
#include <CDynamicWrapperEx.hpp>
Public Member Functions
CDynamicWrapperEx ()
Constructor.
virtual ~CDynamicWrapperEx ()
Destructor.
virtual HRESULT STDMETHODCALLTYPE QueryInterface (_In_ REFIID riid, _Out_ LPVOID *ppvObject)
Queries a COM object for a pointer to one of its interface.
virtual ULONG STDMETHODCALLTYPE AddRef (VOID)
Increment the number of references.
virtual ULONG STDMETHODCALLTYPE Release (VOID)
Decrement the number of references.
virtual HRESULT STDMETHODCALLTYPE CreateInstance (_In_ IUnknown *pUnkOuter, _In_ REFIID riid, _Out_ LPVOID *ppvObject)
Creates an uninitialized object.
virtual HRESULT STDMETHODCALLTYPE LockServer (_In_ BOOL fLock)
Locks an object application open in memory. This enables instances to be created more quickly.
Private Attributes
DWORD m_dwReference { 0 }
Number of reference to the object.
IDynamicWrapperEx * m_pIDynamicWrapperEx { nullptr }
Unique pointer to an IDynamicWrapperEx COM Automation object.
Detailed Description
DynamicWrapperEx class factory.
Definition at line 28 of file CDynamicWrapperEx.hpp.
Constructor & Destructor Documentation
CDynamicWrapperEx()
CDynamicWrapperEx::CDynamicWrapperEx ()
Constructor.
Definition at line 20 of file CDynamicWrapperEx.cpp.
 { }
~CDynamicWrapperEx()
CDynamicWrapperEx::~CDynamicWrapperEx () virtual
Destructor.
Definition at line 25 of file CDynamicWrapperEx.cpp.
 { }
Member Function Documentation
AddRef()
ULONG STDMETHODCALLTYPE CDynamicWrapperEx::AddRef (VOID) virtual
Increment the number of references.
Returns
Number of remaining references.
Definition at line 51 of file CDynamicWrapperEx.cpp.
{
     return InterlockedIncrement(&this->m_dwReference);
 }
Referenced by QueryInterface().
CreateInstance()
HRESULT STDMETHODCALLTYPE CDynamicWrapperEx::CreateInstance (_In_ IUnknown * pUnkOuter, _In_ REFIID riid, _Out_ LPVOID * ppvObject) virtual
Creates an uninitialized object.
Parameters
pUnkOuter Address to an IUknown interface if part of an aggregation.
riid A reference to the identifier of the interface to be used to communicate with the newly created object.
ppvObject The address of pointer variable that receives the interface pointer requested in riid.
Returns
Whether the object has been successfully created.
Definition at line 70 of file CDynamicWrapperEx.cpp.
   {
     if (pUnkOuter != NULL)
         return CLASS_E_NOAGGREGATION;
     IDynamicWrapperEx* pIDynamicWrapperEx = new IDynamicWrapperEx();
     if (pIDynamicWrapperEx == nullptr)
         return E_OUTOFMEMORY;
     HRESULT hr = pIDynamicWrapperEx->QueryInterface(riid, ppvObject);
     this->m_pIDynamicWrapperEx = reinterpret_cast<IDynamicWrapperEx*>(ppvObject);
     pIDynamicWrapperEx->Release();
     return hr;
 }
LockServer()
HRESULT STDMETHODCALLTYPE CDynamicWrapperEx::LockServer (_In_ BOOL fLock) virtual
Locks an object application open in memory. This enables instances to be created more quickly.
Parameters
fLock If TRUE, increments the lock count; if FALSE, decrements the lock count.
Returns
Whether the function executed successfully.
Definition at line 93 of file CDynamicWrapperEx.cpp.
   {
     return ::CoLockObjectExternal(this, fLock, TRUE);
 }
QueryInterface()
HRESULT STDMETHODCALLTYPE CDynamicWrapperEx::QueryInterface (_In_ REFIID riid, _Out_ LPVOID * ppvObject) virtual
Queries a COM object for a pointer to one of its interface.
Parameters
riid A reference to the interface identifier (IID) of the interface being queried for.
ppvObject The address of a pointer to an interface with the IID specified in the riid parameter.
Returns
Whether an interface has been found.
Definition at line 33 of file CDynamicWrapperEx.cpp.
   {
     if (riid == IID_IUnknown || riid == IID_IClassFactory || riid == CLSID_CDynamicWrapperEx) {
         *ppvObject = this;
         this->AddRef();
         return S_OK;
     }
     *ppvObject = NULL;
     return E_NOINTERFACE;
 }
Referenced by DllGetClassObject().
Release()
ULONG STDMETHODCALLTYPE CDynamicWrapperEx::Release (VOID) virtual
Decrement the number of references.
Returns
Number of remaining references.
Definition at line 59 of file CDynamicWrapperEx.cpp.
{
     return InterlockedDecrement(&this->m_dwReference);
 }
Referenced by DllGetClassObject().
Member Data Documentation
m_dwReference
DWORD CDynamicWrapperEx::m_dwReference { 0 } private
Number of reference to the object.
Definition at line 89 of file CDynamicWrapperEx.hpp.
Referenced by AddRef(), and Release().
m_pIDynamicWrapperEx
IDynamicWrapperEx* CDynamicWrapperEx::m_pIDynamicWrapperEx { nullptr } private
Unique pointer to an IDynamicWrapperEx COM Automation object.
Definition at line 94 of file CDynamicWrapperEx.hpp.
Referenced by CreateInstance().
The documentation for this class was generated from the following files:
inc/CDynamicWrapperEx.hpp
src/CDynamicWrapperEx.cpp