DynamicWrapperEx: IDynamicWrapperEx Class Reference
IDynamicWrapperEx Class Reference
DynamicWrapperEx Automation Interface.
#include <IDynamicWrapperEx.hpp>
Public Member Functions
IDynamicWrapperEx ()
Constructor.
virtual ~IDynamicWrapperEx ()
Destructor.
virtual HRESULT STDMETHODCALLTYPE QueryInterface (_In_ REFIID riid, _Out_ LPVOID *ppvObject)
Queries a COM object for a pointer to one of its interface.
virtual ULONG STDMETHODCALLTYPE AddRef (VOID)
Increment the number of references.
virtual ULONG STDMETHODCALLTYPE Release (VOID)
Decrement the number of references.
virtual HRESULT STDMETHODCALLTYPE GetTypeInfoCount (_Out_ UINT *pctinfo)
Retrieves the number of type information interfaces that an object provides (either 0 or 1).
virtual HRESULT STDMETHODCALLTYPE GetTypeInfo (_In_ UINT iTInfo, _In_ LCID lcid, _Out_ ITypeInfo **ppTInfo)
Retrieves the type information for an object, which can then be used to get the type information for an interface.
virtual HRESULT STDMETHODCALLTYPE GetIDsOfNames (_In_ REFIID riid, _In_ LPOLESTR *rgszNames, _In_ UINT cNames, _In_ LCID lcid, _Out_ DISPID *rgDispId)
Maps a single member and an optional set of argument names to a corresponding set of integer DISPIDs, which can be used on subsequent calls to Invoke.
virtual HRESULT STDMETHODCALLTYPE Invoke (_In_ DISPID dispIdMember, _In_ REFIID riid, _In_ LCID lcid, _In_ WORD wFlags, _In_ DISPPARAMS *pDispParams, _Out_ VARIANT *pVarResult, _Out_ EXCEPINFO *pExcepInfo, _Out_ UINT *puArgErr)
Provides access to properties and methods exposed by an object.
Private Attributes
DWORD m_dwReference { 0 }
Number of reference to the object.
std::unique_ptr< AutomationFactory > m_pAutomationFactory { std::make_unique<AutomationFactory>() }
Unique pointer to an AutomationFactory class.
Detailed Description
DynamicWrapperEx Automation Interface.
Definition at line 30 of file IDynamicWrapperEx.hpp.
Constructor & Destructor Documentation
IDynamicWrapperEx()
IDynamicWrapperEx::IDynamicWrapperEx ()
Constructor.
Definition at line 22 of file IDynamicWrapperEx.cpp.
{
     this->m_pAutomationFactory->m_aDispatchTable.push_back({ 0, L"DwRegister"});
     this->m_pAutomationFactory->m_aDispatchTable.push_back({ 1, L"WriteByte" });
     this->m_pAutomationFactory->m_dwInternalMethods = this->m_pAutomationFactory->m_aDispatchTable.size();
 }
~IDynamicWrapperEx()
IDynamicWrapperEx::~IDynamicWrapperEx () virtual
Destructor.
Definition at line 32 of file IDynamicWrapperEx.cpp.
 { }
Member Function Documentation
AddRef()
ULONG STDMETHODCALLTYPE IDynamicWrapperEx::AddRef (VOID) virtual
Increment the number of references.
Returns
Number of remaining references.
Definition at line 58 of file IDynamicWrapperEx.cpp.
{
     return InterlockedIncrement(&this->m_dwReference);
 }
Referenced by QueryInterface().
GetIDsOfNames()
HRESULT STDMETHODCALLTYPE IDynamicWrapperEx::GetIDsOfNames (_In_ REFIID riid, _In_ LPOLESTR * rgszNames, _In_ UINT cNames, _In_ LCID lcid, _Out_ DISPID * rgDispId) virtual
Maps a single member and an optional set of argument names to a corresponding set of integer DISPIDs, which can be used on subsequent calls to Invoke.
Parameters
riid Reserved for future use. Must be IID_NULL.
rgszNames The array of names to be mapped.
cNames The count of the names to be mapped.
lcid The locale context in which to interpret the names.
rgDispId Caller-allocated array, each element of which contains an identifier (ID) corresponding to one of the names passed in the rgszNames array.
Returns
Whether the function executed successfully.
Definition at line 108 of file IDynamicWrapperEx.cpp.
   {
     if (riid != IID_NULL)
         return DISP_E_UNKNOWNINTERFACE;
     for (auto& elem : this->m_pAutomationFactory->m_aDispatchTable) {
         if (::wcscmp(elem.wszName, *rgszNames) == 0) {
             *rgDispId = elem.lDispId;
             return S_OK;
         }
     }
     *rgDispId = 0;
     return E_FAIL;
 }
GetTypeInfo()
HRESULT STDMETHODCALLTYPE IDynamicWrapperEx::GetTypeInfo (_In_ UINT iTInfo, _In_ LCID lcid, _Out_ ITypeInfo ** ppTInfo) virtual
Retrieves the type information for an object, which can then be used to get the type information for an interface.
Parameters
iTInfo The type information to return. Pass 0 to retrieve type information for the IDispatch implementation.
lcid The locale identifier for the type information.
ppTInfo The requested type information object.
Returns
Whether the function executed successfully.
Definition at line 90 of file IDynamicWrapperEx.cpp.
   {
     *ppTInfo = NULL;
     return S_OK;
 }
GetTypeInfoCount()
HRESULT STDMETHODCALLTYPE IDynamicWrapperEx::GetTypeInfoCount (_Out_ UINT * pctinfo) virtual
Retrieves the number of type information interfaces that an object provides (either 0 or 1).
Parameters
pctinfo The number of type information interfaces provided by the object.
Returns
Method not implemented.
Definition at line 76 of file IDynamicWrapperEx.cpp.
   {
     *pctinfo = 1;
     return E_NOTIMPL;
 }
Invoke()
HRESULT STDMETHODCALLTYPE IDynamicWrapperEx::Invoke (_In_ DISPID dispIdMember, _In_ REFIID riid, _In_ LCID lcid, _In_ WORD wFlags, _In_ DISPPARAMS * pDispParams, _Out_ VARIANT * pVarResult, _Out_ EXCEPINFO * pExcepInfo, _Out_ UINT * puArgErr) virtual
Provides access to properties and methods exposed by an object.
Parameters
dispIdMember Identifies the member.
riid Reserved for future use. Must be IID_NULL.
lcid The locale context in which to interpret arguments.
wFlags Flags describing the context of the Invoke call.
pDispParams Pointer to a DISPPARAMS structure containing an array of arguments, an array of argument DISPIDs for named arguments, and counts for the number of elements in the arrays.
pVarResult Pointer to the location where the result is to be stored, or NULL if the caller expects no result.
pExcepInfo Pointer to a structure that contains exception information.
puArgErr The index within rgvarg of the first argument that has an error.
Returns
Whether the function executed successfully.
Definition at line 141 of file IDynamicWrapperEx.cpp.
   {
     if (riid != IID_NULL)
         return DISP_E_UNKNOWNINTERFACE;
     if ((wFlags & DISPATCH_METHOD) != DISPATCH_METHOD)
         return E_FAIL;
     // Non-dynamic methods
     if (dispIdMember == 0)
         return this->m_pAutomationFactory->Register(pDispParams, pVarResult);
     else if (dispIdMember == 1)
         return Util::WriteByte(pDispParams, pVarResult);
     // Execute dynamic method
     HRESULT hr = this->m_pAutomationFactory->m_aDynamicMethods[dispIdMember - this->m_pAutomationFactory->m_dwInternalMethods]->Invoke(pDispParams, pVarResult);
     return hr;
 }
QueryInterface()
HRESULT STDMETHODCALLTYPE IDynamicWrapperEx::QueryInterface (_In_ REFIID riid, _Out_ LPVOID * ppvObject) virtual
Queries a COM object for a pointer to one of its interface.
Parameters
riid A reference to the interface identifier (IID) of the interface being queried for.
ppvObject The address of a pointer to an interface with the IID specified in the riid parameter.
Returns
Whether an interface has been found.
Parameters
riid A reference to the interface identifier(IID) of the interface being queried for.
ppvObject The address of a pointer to an interface with the IID specified in the riid parameter.
Returns
Whether an interface has been found.
Definition at line 40 of file IDynamicWrapperEx.cpp.
   {
     if (IsEqualGUID(riid, IID_IDynamicWrapperEx) || IsEqualGUID(riid, IID_IDispatch) || IsEqualGUID(riid, IID_IUnknown)) {
         *ppvObject = this;
         this->AddRef();
         return S_OK;
     }
     *ppvObject = NULL;
     return E_NOINTERFACE;
 }
Referenced by CDynamicWrapperEx::CreateInstance().
Release()
ULONG STDMETHODCALLTYPE IDynamicWrapperEx::Release (VOID) virtual
Decrement the number of references.
Returns
Number of remaining references.
Definition at line 66 of file IDynamicWrapperEx.cpp.
{
     ULONG ulReference = InterlockedDecrement(&this->m_dwReference);
     return ulReference;
 }
Referenced by CDynamicWrapperEx::CreateInstance().
Member Data Documentation
m_dwReference
DWORD IDynamicWrapperEx::m_dwReference { 0 } private
Number of reference to the object.
Definition at line 131 of file IDynamicWrapperEx.hpp.
Referenced by AddRef(), and Release().
m_pAutomationFactory
std::unique_ptr<AutomationFactory> IDynamicWrapperEx::m_pAutomationFactory { std::make_unique<AutomationFactory>() } private
Unique pointer to an AutomationFactory class.
Definition at line 136 of file IDynamicWrapperEx.hpp.
Referenced by GetIDsOfNames(), IDynamicWrapperEx(), and Invoke().
The documentation for this class was generated from the following files:
inc/IDynamicWrapperEx.hpp
src/IDynamicWrapperEx.cpp